Add SEO fields to product and category models and make editable in the dashboard #3510
django-oscar/django-oscar pull request #3522
Opened 2020-09-29 06:31 UTC by ajharry69

2020-10-02 04:50 UTC, solarissmoke requested changes

2020-10-02 04:50 UTC, solarissmoke commented on src/oscar/apps/dashboard/catalogue/forms.py
> +    def is_seo_field(field):
It is better to explicitly define on the class itself which fields are considered SEO fields, so that projects can override.

2020-10-02 04:50 UTC, solarissmoke commented on src/oscar/apps/dashboard/catalogue/forms.py
> +        if 'meta_description' in self.fields:
Don't think we need to do this at init - can do it when defining the field itself, i.e., 

```
meta_description = models.TextField(_('Meta Description'), blank=True, widget=forms.TextArea(attrs={'class': 'no-widget-init'})
```

2020-10-02 04:50 UTC, solarissmoke commented on src/oscar/templates/oscar/base.html
> +        <meta name="title" content="{% block meta_title %}{% endblock %}" />
This is not a valid element. The title needs to go into the `<title>` tag, for which we already have a `{% block title %}`. The `catalogue/detail.html` and `catalogue/browse.html` templates override this block and we need to adjust the content inside each.

2020-10-02 04:50 UTC, solarissmoke commented on src/oscar/templates/oscar/catalogue/detail.html
> +{% block meta_title %}
Need to change `{% block title %}` above, rather than adding a new block.

2020-10-02 04:50 UTC, solarissmoke commented on src/oscar/apps/catalogue/abstract_models.py
> +    meta_title = models.CharField(_('Meta Title'), max_length=255, blank=True, db_index=True)
We don't need a database index on this field.

2020-10-02 04:50 UTC, solarissmoke commented on src/oscar/apps/dashboard/catalogue/forms.py
> +    def visible_fields(self):
`visible_fields` has a specific meaning in Django forms, and I don't think we should override that here. Suggest we have a separate method e.g., `primary_form_fields` which returns the fields we render in the main tab, and then use that in the template.

2020-10-02 04:50 UTC, solarissmoke commented on src/oscar/templates/oscar/dashboard/catalogue/category_form.html
> +                        <ul class="nav nav-list bs-docs-sidenav" id="product_update_tabs">
`id="product_update_tabs"` has been copied from the product form, but isn't semantically correct for a category form.

2020-10-05 04:37 UTC, solarissmoke commented
@ajharry69 something has gone wrong with the migrations for this change - you seem to have deleted the migrations that actually create the new fields. Please delete all your migrations, and regenerate afresh. Also please rebase this PR onto master - currently the diff if showing lots of changes that are not related to this feature.

2020-10-05 04:37 UTC, solarissmoke commented on src/oscar/apps/catalogue/abstract_models.py
> +    meta_title = models.CharField(_('Meta-title'), max_length=255, blank=True)
Please change the label to "Meta title" instead of "Meta-title". Some for all other other fields below - please remove hyphen.

2020-10-05 04:38 UTC, solarissmoke commented on src/oscar/apps/dashboard/catalogue/forms.py
> +import re
Unused import.

2020-10-05 08:34 UTC, closed without merging

2020-10-05 08:37 UTC, ajharry69 commented
Created a [new PR](https://github.com/django-oscar/django-oscar/pull/3534).