Make inactive products and categories identifiable in dashboard list …
django-oscar/django-oscar pull request #3538
Opened 2020-10-08 12:30 UTC by capelito

Refs #3536

2020-10-09 05:22 UTC, solarissmoke requested changes

2020-10-09 05:22 UTC, solarissmoke commented on src/oscar/apps/dashboard/catalogue/tables.py
> +        sequenze = ('name', 'description', '...', 'is_public', 'actions')
`sequenze`  should be `sequence`. Also please check the failing lint errors.

2020-10-09 12:09 UTC, solarissmoke requested changes
This looks good for the main tables. We also need to update the table that displays variants for a product (the "Variants" tab of the product edit view) - could you please add a column there as well?

2020-10-09 15:10 UTC, capelito commented
Thanks for your feedback, I used the true/false icons to make the status identifiable. Some other views use like  /dashboard/ranges/ use Yes or No. What do you prefer?

2020-10-12 07:24 UTC, solarissmoke commented
> I used the true/false icons to make the status identifiable. Some other views (for example /dashboard/ranges/) use Yes or No.

Hmm, I think the true/false are easier to parse visually, so would suggest we use those. I'm going to wait until #3302 is merged before merging this though, so that we can check that the icons still work after we switch to Bootstrap 4.

2020-10-12 07:26 UTC, solarissmoke commented
That said I'm not sure whether unicode icons are good from an accessibility perspective. There are probably some guidelines on this sort of thing somewhere which we can refer to - will see if I can find any.

2020-10-19 11:54 UTC, solarissmoke approved these changes
Thanks for this - looks good. The accessibility question I mentioned earlier is best addressed separately, as there are currently a lot of accessibility issues in the dashboard.

2020-10-19 11:55 UTC, merged