Add MIR support
django-oscar/django-oscar pull request #3604
Opened 2020-12-23 13:43 UTC by gormih

Add system MIR to supported payments cards

2020-12-23 13:44 UTC, gormih commented
MIR - is new Russian payments system.

2021-01-04 09:40 UTC, solarissmoke requested changes

2021-01-04 09:40 UTC, solarissmoke commented on src/oscar/apps/payment/bankcards.py
> +    (MIR, (16), ('2')),
Both these need to be tuples, for which a trailing comma is required inside each bracket. 

Also from [the Wikipedia entry](https://en.wikipedia.org/wiki/Payment_card_number) for this, the prefixes are a bit more complex than just `2` - I think an approach similar to what has been used for Discover above is required.

2021-09-16 06:44 UTC, solarissmoke commented
Closing due to inactivity - feel free to reopen with the requested changes.

2021-09-16 06:44 UTC, closed without merging