Handle EventHandler extra kwagrs arguments.
django-oscar/django-oscar pull request #3752
Opened 2021-08-05 10:07 UTC by akash-vns

represented PR for - https://github.com/django-oscar/django-oscar/issues/3749
 
 Here we can accept the extra kwargs with ```get_handler_kwargs()``` method.

2021-08-20 10:34 UTC, solarissmoke requested changes

2021-08-20 10:34 UTC, solarissmoke commented on src/oscar/apps/order/mixins.py
> +        kwargs = dict()
Please change this to `return {}`

2021-09-01 04:34 UTC, kaushaltrootech commented on src/oscar/apps/order/mixins.py
> +class EventHandlerMixin(object):
Okay

2021-09-01 04:34 UTC, kaushaltrootech commented on src/oscar/apps/order/mixins.py
> +    """
Okay sure

2021-09-01 04:35 UTC, kaushaltrootech commented on src/oscar/apps/order/mixins.py
> +        kwargs = dict()
Okay sure

2021-09-08 06:25 UTC, solarissmoke commented on src/oscar/apps/order/mixins.py
> +    """
This doesn't seem to have been addressed?

2021-09-14 10:43 UTC, merged