Implement shareable wishlists
django-oscar/django-oscar pull request #3905
Opened 2022-04-01 12:04 UTC by joeyjurjens

Partly implements #3509 .

This PR makes it possible to share your wish list link with other people.
There are three types of wish lists:
1. Private
  - Only available for the owner of the wish list.
 2. Shared
   - Available for the owner and emails the owner has set for access. This requires people to create an account with this email in order to view it (if they didn't yet). The reason for a email field instead of a user field is that I don't think customers should be able to select users.
 3. Public
   - Available for everyone, also non logged in users. We could add no-index and no-follow tags so robots don't index the page, but I think a public wish list should not require a login but we can discuss about it.

The shared wish list does **not** allow editing the wish list (except owner of course).

As the issue also states: "it seems the original intention behind this was to have lists that can collaboratively be managed by multiple users. The use case for this isn't clear to me, and I think needs elaboration before we can implement."

So I haven't implemented any of that. We could add a new field "allow_edit" on the newly created model and then implement from there.

2022-04-11 08:53 UTC, viggo-devries requested changes

2022-04-11 08:53 UTC, viggo-devries commented on src/oscar/templates/oscar/customer/wishlists/wishlists_form.html
> +                {% trans "Add the emails from the people you want to share your wishlist with. The wishlist visibility must be set to shared if you want to share it with certain people only." %}
I think this should be a different text

2022-05-23 08:13 UTC, viggo-devries requested changes

2022-05-23 08:13 UTC, viggo-devries commented on src/oscar/apps/wishlists/views.py
> +            print(settings.LOGIN_REDIRECT_URL)
print

2022-05-23 08:13 UTC, viggo-devries commented on src/oscar/apps/wishlists/views.py
> +            return redirect(settings.LOGIN_REDIRECT_URL)
is it maybe possible to add a ?next parameter to redirect the user to the wishlist after logging in?

2022-05-23 08:13 UTC, viggo-devries commented on src/oscar/apps/wishlists/views.py
> +            return redirect(settings.LOGIN_REDIRECT_URL)
is it maybe possible to add a ?next parameter to redirect the user to the wishlist after logging in?

2022-06-01 09:39 UTC, viggo-devries approved these changes

2022-06-22 13:36 UTC, specialunderwear requested changes
I think we need a native english speaker to review the help messages @solarissmoke

2022-06-22 13:36 UTC, specialunderwear commented on src/oscar/apps/wishlists/abstract_models.py
> +            return self.shared_emails.filter(models.Q(email=user.email)).exists()
why models.Q?

2022-06-22 13:36 UTC, specialunderwear commented on src/oscar/apps/wishlists/views.py
> +            messages.info(request, _("Please login with the email address that is shared to this wish list."))
I don't think this message is a clear way of handling not allowed to see the message. I think you should only redirect to login if the user is anonymoes, and simply state "You are not allowed to see this wishlist", 403 if sombody is logged in but not allowed to view the wishlist.

2022-06-22 14:44 UTC, specialunderwear submitted a review, later dismissed

2022-06-24 05:29 UTC, solarissmoke requested changes
Couple of minor string changes requested, otherwise looks good.

2022-06-24 05:29 UTC, solarissmoke commented on src/oscar/templates/oscar/customer/wishlists/wishlists_form.html
> +                {% trans "If you want to share your wishlist with other accounts, you can add their emails below. The visibility must be set to shared in order for this to work." %}
Please amend the first sentence to: "If you want to share your wishlist with others, you can add their email addresses below."

2022-06-24 05:29 UTC, solarissmoke commented on src/oscar/templates/oscar/customer/wishlists/wishlists_list.html
> +                                        {% trans 'Copy shared link' %}
I think "copy sharing link" makes more sense.

2022-06-24 07:19 UTC, joeyjurjens commented
> Couple of minor string changes requested, otherwise looks good.

I've applied your change requests

2022-06-24 08:17 UTC, solarissmoke approved these changes

2022-06-24 08:18 UTC, merged