Atomically consume allocations and stock
django-oscar/django-oscar pull request #3922
Opened 2022-05-12 15:31 UTC by viggo-devries

2022-05-13 05:14 UTC, specialunderwear requested changes

2022-05-13 05:14 UTC, specialunderwear commented on src/oscar/apps/partner/abstract_models.py
> +                num_allocated=min(Coalesce(F("num_allocated"), Value(0)) - quantity),
min?

2022-05-18 07:38 UTC, specialunderwear approved these changes

2022-05-20 13:49 UTC, joeyjurjens approved these changes

2022-05-20 13:49 UTC, merged