Only change order line status when status is available
django-oscar/django-oscar pull request #3948
Opened 2022-07-08 12:05 UTC by viggo-devries

It's possible for lines to have a completely different status than the order.
When a line is at an "end status" where it cannot change anymore this will result in the line being changed to something you might not want.

2022-07-08 12:06 UTC, specialunderwear requested changes
please add a test

2022-07-08 12:06 UTC, sasha0 commented
Needs test.

2022-07-08 12:06 UTC, viggo-devries commented
hahah definitely tests, was curious if the current tests would still pass.

2022-08-08 12:24 UTC, specialunderwear requested changes

2022-08-08 12:24 UTC, specialunderwear commented on src/oscar/apps/order/abstract_models.py
> +                if new_status in line.available_statuses():
```if self.cascade[new_status] in line.available_statuses():```

2023-06-02 14:01 UTC, joeyjurjens approved these changes

2023-06-16 09:22 UTC, specialunderwear approved these changes

2023-06-16 09:22 UTC, merged