show boolean option value to yes/no in stead of true/false
django-oscar/django-oscar pull request #4005
Opened 2022-11-15 16:22 UTC by wlaw01

2022-11-16 08:11 UTC, joeyjurjens commented
Can you also add unit tests here?
https://github.com/django-oscar/django-oscar/blob/1f84c57e0675dd3adef1f116cbf36c507017893a/tests/integration/catalogue/test_attributes.py#L10

2022-11-16 09:15 UTC, specialunderwear requested changes

2022-11-16 09:15 UTC, specialunderwear commented on src/oscar/apps/catalogue/abstract_models.py
> +            return (_("Yes"))
why not ```_("Yes")```?

2022-11-16 16:32 UTC, wlaw01 commented on src/oscar/apps/catalogue/abstract_models.py
> +            return (_("Yes"))
i forgot to remove it. its fixed now

2022-11-18 08:10 UTC, specialunderwear approved these changes

2022-11-18 08:10 UTC, merged