Non-public Products are shown in Offers
django-oscar/django-oscar pull request #4053
Opened 2023-02-20 10:33 UTC by gwaidacher

AbstractRange.product_queryset() provides non-public Products.

added `.filter(is_public=True)` in AbstractRange.product_queryset()

2023-02-23 08:46 UTC, joeyjurjens approved these changes

2023-02-24 09:31 UTC, viggo-devries commented
@gwaidacher could you please provide a unit test that shows this is working?

2023-02-24 09:34 UTC, viggo-devries commented
@joeyjurjens maybe this should use the .browsable method ? It could result in some weird results when customising the browsable method though.

2023-02-24 09:42 UTC, gwaidacher commented
> @joeyjurjens maybe this should use the .browsable method ? It could result in some weird results when customising the browsable method though.

This is exactly what I thought about this morning, I will do so

2023-02-24 09:46 UTC, joeyjurjens commented
> @joeyjurjens maybe this should use the .browsable method ? It could result in some weird results when customising the browsable method though.

Yeah I thought about that as well, but since products without categories could technically still be ordered, I thought I'd let it be. But it's probably best to use .browsable() to keep consistency, people can always override the browsable() implementation.

2023-02-24 09:48 UTC, gwaidacher commented
> @gwaidacher could you please provide a unit test that shows this is working?

where should this test be located?

2023-02-24 10:06 UTC, viggo-devries commented
> > @gwaidacher could you please provide a unit test that shows this is working?
> 
> where should this test be located?

Probably somewhere in here? https://github.com/django-oscar/django-oscar/blob/master/tests/integration/offer/test_range.py#L259

2023-02-24 10:28 UTC, gwaidacher commented
> > @joeyjurjens maybe this should use the .browsable method ? It could result in some weird results when customising the browsable method though.
> 
> Yeah I thought about that as well, but since products without categories could technically still be ordered, I thought I'd let it be. But it's probably best to use .browsable() to keep consistency, people can always override the browsable() implementation.

Tests failed @tests/functional/dashboard/test_range.py in test_adding_child_does_not_add_parent() using browsable()

I worried about that before, since browsable() excludes child products... should I return to the previous Version using `filter(is_public=True)`

{{{
    def browsable(self):
        """
        Excludes non-canonical products and non-public products
        """
        return self.filter(parent=None, is_public=True)
}}}

2023-02-24 10:56 UTC, viggo-devries requested changes

2023-02-24 10:56 UTC, viggo-devries commented on tests/integration/offer/test_range.py
> +        product = create_product()
create_product(is_public=False)

2023-02-24 10:56 UTC, viggo-devries commented on tests/integration/offer/test_range.py
> +        self.range.remove_product(product)
you don't need to remove the product here, it's just test data

2023-02-24 11:03 UTC, gwaidacher commented
> > @joeyjurjens maybe this should use the .browsable method ? It could result in some weird results when customising the browsable method though.
> 
> Yeah I thought about that as well, but since products without categories could technically still be ordered, I thought I'd let it be. But it's probably best to use .browsable() to keep consistency, people can always override the browsable() implementation.

Because of the failure in dashboard-integration test I think it would be much better to exclude them later in apps/offer/views.py, OfferDetailView.get_queryset(): return self.offer.products().browsable()

2023-02-24 11:10 UTC, viggo-devries commented
> > > @joeyjurjens maybe this should use the .browsable method ? It could result in some weird results when customising the browsable method though.
> > 
> > 
> > Yeah I thought about that as well, but since products without categories could technically still be ordered, I thought I'd let it be. But it's probably best to use .browsable() to keep consistency, people can always override the browsable() implementation.
> 
> Because of the failure in dashboard-integration test I think it would be much better to exclude them later in apps/offer/views.py, OfferDetailView.get_queryset(): return self.offer.products().browsable()

I discussed this with Joey really quickly and I think we're approaching this the wrong way, you are trying to remove non public products from the Range detail view right? I didn't see the original issue you were basing this on.
That being said I think you should add .browsable right here:
https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/offer/abstract_models.py#L454

And then add a test that check if the conditional offer products method returns only browsable products.

2023-02-24 11:11 UTC, viggo-devries commented
> > > @joeyjurjens maybe this should use the .browsable method ? It could result in some weird results when customising the browsable method though.
> > 
> > 
> > Yeah I thought about that as well, but since products without categories could technically still be ordered, I thought I'd let it be. But it's probably best to use .browsable() to keep consistency, people can always override the browsable() implementation.
> 
> Because of the failure in dashboard-integration test I think it would be much better to exclude them later in apps/offer/views.py, OfferDetailView.get_queryset(): return self.offer.products().browsable()

HA just what I thought.

2023-02-24 11:17 UTC, viggo-devries requested changes

2023-02-24 11:17 UTC, viggo-devries commented on src/oscar/apps/offer/views.py
> +        return self.offer.products().browsable()
please do this on the model method

2023-02-24 11:17 UTC, viggo-devries commented on src/oscar/templates/oscar/offer/list.html
> +                {% for product in offer.products.browsable|slice:":12" %}
if you do .browsable on the model method this is not needed.

2023-02-24 11:17 UTC, viggo-devries commented on src/oscar/apps/offer/abstract_models.py
> +        # Filter out non-public Products
remove comment.

2023-02-24 11:36 UTC, gwaidacher commented on src/oscar/apps/offer/abstract_models.py
> +        # Filter out non-public Products
done

2023-02-24 11:37 UTC, gwaidacher commented on src/oscar/apps/offer/views.py
> +        return self.offer.products().browsable()
done

2023-02-24 11:39 UTC, viggo-devries commented on src/oscar/apps/offer/abstract_models.py
>          return queryset.filter(is_discountable=True).exclude(
En then you can remove the .exclude since this is also done in browsable :)

2023-02-24 11:40 UTC, viggo-devries requested changes

2023-02-24 11:40 UTC, viggo-devries commented on src/oscar/apps/offer/abstract_models.py
> -
no newline

2023-02-24 11:41 UTC, viggo-devries commented on src/oscar/apps/offer/abstract_models.py
>          return queryset.filter(is_discountable=True).exclude(
https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/catalogue/managers.py#L108

see parent=None is the same as .exclude(structure=CHILD)

2023-02-24 12:07 UTC, gwaidacher commented
I think we got it the right way round now, sometimes I think too complicated while there exists an easier way to solve a problem...

2023-02-24 12:43 UTC, viggo-devries commented
> I think we got it the right way round now, sometimes I think too complicated while there exists an easier way to solve a problem...

almost, you now removed .browsable from the range detail view, this does not use the offer.products method.
https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/offer/views.py#L71

I do think this should be in place here otherwise the range detail will stil show non public products.

2023-02-24 13:37 UTC, viggo-devries commented
please also provide test for the range view, cannot be merged because the hit target was not met...

2023-02-24 13:57 UTC, viggo-devries requested changes

2023-02-24 13:57 UTC, viggo-devries commented on tests/integration/offer/test_offer.py
> +        self.assertFalse(
This is not sufficient unfortunately, you need to test the RangeDetail view. this is just executing the code you added to the view.

2023-02-24 13:58 UTC, viggo-devries approved these changes

2023-03-01 09:43 UTC, viggo-devries approved these changes

2023-03-01 09:44 UTC, merged