Speed up Range.product_queryset()
django-oscar/django-oscar pull request #4066
Opened 2023-03-03 09:46 UTC by gwaidacher

…d/or no children in products.

Reduce joins in Range.product_queryset() if there are no classes in the range and / or included products have no children. 

see #4043 for more details, this patch fixes the issue

rebased #4042

2023-03-03 10:21 UTC, gwaidacher commented
Could you please explain the joins over parent_ids (see #4043) - is this used when a child product is addet to the range, so it's parent is automatically included and shown in the offer, the child is excluded in the offer via browsable()?

2023-03-10 12:03 UTC, gwaidacher commented
Thank you, specialunderwear, for your detailed answer.

> I think it would be much easier to just offer the browsable method on range and alter the offers.
The browsable() method in RangeDetailView was already merged from my PR into master a week ago, see https://github.com/django-oscar/django-oscar/pull/4053 "Exclude non-public Products from Offer - https://github.com/django-oscar/django-oscar/commit/75ed8827bd9a1c2a7613e41f7f08974e3c747530

We have a demo-shop running at https://shop.acat.cc, where my patch is running; the speeded up offer is at https://shop22/en/offers/oster-2023/

Variants are not planned in our shop in the near future; we have a very fast designated database server with SSD disks, and we will keep the changes in the forked range queryset to avoid response times over 10 seconds in our offers.

Concerning a worst case scenario, we would not copy 3000000 into included_products, but picking up all products via range.includes_all_products having unwanted in excluded_products - this would be the first response in range.product_queryset(), not touching the queries with tests if classes or children exist.

Adding classes to the range would not worsen the performance by the query  `if self.classes.exists()`.

The worst case is - like before - if self.included_categories.exists() and self.classes.exists() leading to the original query with the response time of > 10 seconds.  This scenario is not worsened significant by this two queries, which are very fast.

All other scenarios have reduced joins and the single check for children is now much faster - from my opinion all scenarios will now gain performance:

I just optimized the query for children:
`if self.included_products.exclude(children=None).exists()` takes a view seconds, so i replaced it with:

`if Product.objects.filter(parent__includes=self).exists()` which is much faster by using indexed field parent_id - but there was a failure in codecov/project, see above, please check.

cheers!

2023-03-13 09:50 UTC, gwaidacher commented
I had another test with a category in the range containing > 1000000 products and added a child to the last product (oldest date_updated):
The original query took over 11 seconds:
Time: 11346.651 ms (00:11.347)

I also added a check for included_products, so the optimized query for the range with category, without classes and included_products could be reduced to 7 seconds:
Time: 7012.940 ms (00:07.013)

All three checks for classes, included_categories and included_products are insignifcant in time.

2023-03-13 10:19 UTC, gwaidacher commented
Hi!

I added another check if included_categories have children and performed some tests measuring 
response times with two ranges including > 1000000 products, please have a look at my comments in the PR

https://github.com/django-oscar/django-oscar/pull/4066


thank you,

-- 
Gunther Waidacher
Acat GmbH
Linke Wienzeile 106/12, A-1060 Wien · Austria


Am 09.03.23 um 09:54 schrieb Voxin Muyli:
>     Could you please explain the joins over parent_ids (see #4043
>     <https://github.com/django-oscar/django-oscar/issues/4043>) - is this used when a child product
>     is addet to the range, so it's parent is automatically included and shown in the offer, the
>     child is excluded in the offer via browsable()?
> 
> Hi I can explain why children are added to the range. But it has nothing to do with offer. Range is 
> a very handy tool by itself that can be used for much more than just offers. So let's see what we 
> got. A range is way to create a queryset from various grouping tools in oscar. eg; a category, a 
> productclass, or manually by including and excluding products. This can be used for many things and 
> in stock oscar it is used for offers.
> 
> The logic of range is tested and one of the tests proves that when a parent product is added to the 
> range, either manually, by category or by means of productclass, the child products should also be 
> contained in the range. You could manually exclude a child product if you want it excluded.
> 
> So you say that there is an offer where the child products are removed from the range again by 
> calling |browsable| on the queryset. That seems like a weird thing to do, because the basket never 
> contains parent products, only child products, so how would that even work? Maybe this functionality 
> is used only for the offers view where all the products that are eligible for the offer are shown? 
> And maybe the children are added again in the check to see if the offer applies? Maybe you should 
> add a method to range: |browsable| that performs the more simple query, excluding the child products 
> and use that in the offers?
> 
> I think it would be much easier to just offer the |browsable| method on range and alter the offers.
> If you do want to improve the overall performance of range, we would need some evidence and 
> explanation showing that the performance has been improved for all worse case scenarios. For example 
> it might be, - the way you designed it now -, the worst case scenario is worsened because an extra 
> query needs to be performed checking for children, which if the last product in the range is the one 
> having children and your queryset is 3000000 you might have worsened the performance by a factor 2. 
> That this is not the case isn't immediately obvious to me and would need some demonstration.
> 
> —
> Reply to this email directly, view it on GitHub 
> <https://github.com/django-oscar/django-oscar/pull/4066#issuecomment-1461593985>, or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/A37MITZ4YCP2EWFGLNREZFTW3GLFRANCNFSM6AAAAAAVOMQM5Y>.
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>
>

2023-03-14 15:09 UTC, specialunderwear commented
> Thank you, specialunderwear, for your detailed answer.
> 
> > I think it would be much easier to just offer the browsable method on range and alter the offers.
> 
> The browsable() method in RangeDetailView was already merged from my PR into master a week ago, see #4053 "Exclude non-public Products from Offer - [75ed882](https://github.com/django-oscar/django-oscar/commit/75ed8827bd9a1c2a7613e41f7f08974e3c747530)

Ok I think we need to roll that back, because browsable does not only filter out non public products but also children @viggo-devries @gwaidacher I think you need to put ``browsable`` in the view so it will not display children and not in the core logic because offers should still apply to children that are in the basket.

Note that I am proposing to add ``browsable`` as a method to ``Range`` - not ``Offer`` - which would return the queryset without children, as you are proposing. So you have a sure way to get a queryset without any children and only public products.

If you still think your current solution with the check is good enough and even better than adding a ``browsable`` method to get a filtered queryset from ``Range``, we will have to first test that in a couple of our own sites, where there are A LOT of children. Because in that case the check might be bad for performance. Some sites we have each product has about 40 children and there are about 300k parents.

2023-03-14 15:13 UTC, specialunderwear commented
One thing that would also be preferable, can you do the check in the database instead of in python, maybe it's possible to not add the extra query that way?

2023-03-15 11:00 UTC, gwaidacher commented
> If you still think your current solution with the check is good enough and even better than adding a `browsable` method to get a filtered queryset from `Range`, we will have to first test that in a couple of our own sites, where there are A LOT of children. Because in that case the check might be bad for performance. Some sites we have each product has about 40 children and there are about 300k parents.


My first efforts by excluding the children earlier in the range queryset did not work, a test checking children in the range failed:
https://github.com/gwaidacher/django-oscar/blob/patch-2/tests/integration/offer/test_range.py#L53

So the browsable() method had to be added in the view:
https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/offer/views.py#L71

My checks for children use exists() - so they return True with the first product with parent_id matching range products found, this is independent of how many children a product has.

I had the original query which took 11 sec run in an analyze tool, which said just collecing merge joins over classes, included_categories and included_products takes over 5 seconds - knowing that we have no classes and categories lead me to the solution to reduce the joins.

I had my tests run in the shell, just fetching the range as 'self' - so I could paste the different queries into the shell, print the query and paste it into database shell to obtain execution time
eg:
self = Range.objects.latest('id')
qs = Product.objects.filter(Q(includes=self) | Q(parent__includes=self) ...)
print(qs.query)

in this way it's also easy to check my switches do not consume significant execution time:
Product.objects.filter(parent__includes=self).exists()
Product.objects.filter(parent__categories__in=expanded_range_categories).exists()

2023-05-05 12:32 UTC, specialunderwear reviewed
I think you can simplify your code a lot if you would not duplicate the entire query in you if statements, but instead build up the filter clause based on the if statements.
something like done here as well: https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/catalogue/managers.py#L39

The code would look something like this then:
```
_filter =  models.Q(includes=self) # start with filter clause that always applies
_exclude_filter = models.Q(excludes=self) # also build and exclude
 if self.classes.exists():
    _filter |= Q(product_class__classes=self)
if Product.objects.filter(parent__includes=self).exists():
    _filter |= Q(parent__includes=self)
    _exclude_filter != Q(parent__excludes=self)

# etc ...

return Product.objects.filter(_filter).exclude(_exclude_filter)
```
Something like that. You can make the code a LOT shorter if you do it like that and perhaps keep it in the single method?

We are reviewing pull requests every week from now on.

2023-05-05 12:32 UTC, specialunderwear commented on src/oscar/apps/offer/abstract_models.py
>                  | Q(product_class__classes=self)
If classes exist, you are skipping the optimization.

2023-05-05 12:32 UTC, specialunderwear commented on src/oscar/apps/offer/abstract_models.py
> +        # check if included_products have children
If classes exist, you are skipping the optimization

2023-05-05 13:02 UTC, specialunderwear requested changes
Please see the above comments on how to simplify these changes.

2023-05-09 12:46 UTC, gwaidacher commented
> Please see the above comments on how to simplify these changes.

Hi! I had a problem with editing the file in my patch-3, so I created a new pull request #4100 for this issue.

2023-05-09 12:54 UTC, gwaidacher commented
Simplified code in #4100, closing this PR

2023-05-09 12:54 UTC, closed without merging