Fixed import of payment and order exclusions in dashboards
django-oscar/django-oscar pull request #4068
Opened 2023-03-03 17:09 UTC by dd

In a dashboard, unlike a checkout, PaymentError and order errors are imported [directly from packages](https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/dashboard/orders/views.py#L15). I replaced the import in the dashboard with a _get_class_ call similar to [checkout](https://github.com/django-oscar/django-oscar/blob/master/src/oscar/apps/checkout/views.py#L21)

2023-03-18 22:07 UTC, joeyjurjens approved these changes

2023-05-05 11:51 UTC, viggo-devries commented
@dd Please write unit test so the code coverage doesn't drop. Thanks!

2023-05-05 13:23 UTC, specialunderwear requested changes

2023-05-05 13:23 UTC, specialunderwear commented on src/oscar/apps/dashboard/orders/views.py
> +InvalidStatus = get_class('order.exceptions', 'InvalidStatus')
Please use get_classes to import multiple classes from the same file

2023-05-26 12:38 UTC, specialunderwear commented
I don't think anyone will ever need to change the exceptions by subclassing.
The get_class mechanism is only needed for this scenario. If you can demonstrate a case where this is needed, feel free to reopen the issue, thank you.

2023-05-26 12:38 UTC, closed without merging