Register discounts per line
django-oscar/django-oscar pull request #4138
Opened 2023-07-19 13:59 UTC by viggo-devries

2023-07-21 15:28 UTC, specialunderwear requested changes

2023-07-21 15:28 UTC, specialunderwear commented on src/oscar/apps/basket/abstract_models.py
> +                - round_half_up(self._tax_ratio * incl_tax_discounts),
This calculation is incorrect if all other prices are calculated from prices ex tax.
This must be checked.

2023-07-21 15:28 UTC, specialunderwear commented on src/oscar/apps/basket/abstract_models.py
> +        elif self.line_price_excl_tax is not None and excl_tax_discounts:
This is unfinshed, it must be checked if the rounding is done at the correct point.

2024-01-04 14:28 UTC, specialunderwear commented on src/oscar/apps/basket/abstract_models.py
> +        elif self.line_price_excl_tax is not None and excl_tax_discounts:
Checked and concluded rounding is not done at the correct point. To fix this issue, oscar should use 4 decimals for all prices internally. Added hint for developers to implement _tax_ratio to get rid of rounding errors.

2024-01-04 14:34 UTC, specialunderwear submitted a review, later dismissed

2024-01-04 14:45 UTC, samar-hassan requested changes

2024-01-04 14:45 UTC, samar-hassan commented on src/oscar/apps/basket/abstract_models.py
> +            # there are discounts that return a value excluding tax, we can simply
```suggestion
            # these are discounts that return a value excluding tax, we can simply
```

2024-01-04 14:50 UTC, samar-hassan approved these changes

2024-01-04 14:51 UTC, merged