Update BasketMiddleware.get_basket() to show warning only if items have been merged
django-oscar/django-oscar pull request #4145
Opened 2023-08-04 11:53 UTC by gwaidacher

Show warning only if merged baskets had  items, including the total number of items that have been merged.

2023-08-08 13:11 UTC, gwaidacher commented
The new "Details" of "Tests / lint_python" do not show the error including the line in the file.
Please help with debugging

2023-08-08 14:09 UTC, specialunderwear commented
Try "make black"

2023-08-09 09:09 UTC, gwaidacher commented
> Try "make black"

Thank you, it worked!

2023-09-08 08:03 UTC, specialunderwear requested changes
Could you add a test that shows this works as intended?

2023-09-08 08:03 UTC, specialunderwear commented on src/oscar/apps/basket/middleware.py
> +                    f"We have merged {num_items_merged} items from a "
Unfortunately f strings don't work in translatable strings yet, please use %(name)s like it's done in other places.

2023-09-08 14:21 UTC, gwaidacher commented
> Could you add a test that shows this works as intended?

I'll try next week; I think I should go this way:

1) add a product to the catalogue
2) add a registered user 
2) call AddToBasketForm() and set the product in form data as anonymous user (WebTestCase)
3) call login-form, login as registered user
4) get context from login (response = form.submit().follow())
5) check response.context['messages']

2023-09-20 08:53 UTC, specialunderwear commented
@gwaidacher why are you always pusing each separate commit? We get a notification of each commit you push, which is a problem with regards to spam. Why don't you finish your feature completely on your computer and then only push when you are done and want to see the test results?

2023-09-20 09:18 UTC, gwaidacher commented
> @gwaidacher why are you always pusing each separate commit? We get a notification of each commit you push, which is a problem with regards to spam. Why don't you finish your feature completely on your computer and then only push when you are done and want to see the test results?

Hi! Sorry, my test is already working in `<our_app>/basket/tests.py` - but I'm unable to get it running in `tests/functional/basket/`
``` 
./manage.py test <our_app>.basket
...
Ran 1 test in 0.900s
OK
```

2023-09-20 10:04 UTC, gwaidacher commented
> @gwaidacher why are you always pusing each separate commit? We get a notification of each commit you push, which is a problem with regards to spam. Why don't you finish your feature completely on your computer and then only push when you are done and want to see the test results?

done, finally! please have a look. I expect tests run always in English, so translating the expected message (test_basket.py, line 114) is not necessary, right?

2024-01-05 17:33 UTC, samar-hassan approved these changes

2024-01-08 13:37 UTC, samar-hassan approved these changes

2024-01-09 08:21 UTC, specialunderwear approved these changes

2024-01-09 08:21 UTC, merged