Fix the collapsed table header
django-oscar/django-oscar pull request #4201
Opened 2023-11-04 10:37 UTC by patrikniebur

When all content is floated (like in stock alerts), the height of the table header collapses. Changing its display value to `flow-root` prevents this from happening. I haven't checked all the uses of `.table-header` but I can't imagine a scenario where this change would break the layout.

### BEFORE
![Screenshot 2023-11-04 at 10 31 42](https://github.com/django-oscar/django-oscar/assets/6452693/b1495cb1-cfee-4234-96db-17b31c00456d)

### AFTER
![Screenshot 2023-11-04 at 10 31 51](https://github.com/django-oscar/django-oscar/assets/6452693/ac9d0d29-624c-4537-b12d-80478bf8c271)

2024-01-02 22:07 UTC, samar-hassan commented
Thanks @patrikniebur for highlighting the styling issue. However, the proposed solution appears to affect other pages using the .table-header class. A more targeted approach might be beneficial. Consider applying the adjustment exclusively to the table on the stock alerts page to avoid interference with other tables.

2024-01-02 22:08 UTC, samar-hassan requested changes
Thanks @patrikniebur for highlighting the styling issue. However, the proposed solution appears to affect other pages using the .table-header class. A more targeted approach might be beneficial. Consider applying the adjustment exclusively to the table on the stock alerts page to avoid interference with other tables.

2024-01-09 08:10 UTC, patrikniebur commented
Hello @samar-hassan. I did consider more targeted approach but it would just reduce the benefits of the change. Currently as it is, it has no effect on tables with at least one non floated child and if all child elements are floated it will prevent from the same issue happening again.

2024-01-29 13:19 UTC, patrikniebur commented
@samar-hassan any further thoughts on this?

2024-01-29 17:25 UTC, samar-hassan commented
@patrikniebur this affects all dashboard pages with table. The layout is distorted. Please check the order and product listing pages for reference.

2024-01-29 20:51 UTC, patrikniebur commented
Thank you @samar-hassan. Sorry I missed these pages the project is still new for me. 

I missed the fact I was changing display property of `caption` element too so I have now separated this style. I've reviewed the pages you suggested and these are now displaying correctly, also all the uses of `table-header` class and made sure this won't cause any other layout problems.

2024-01-31 23:32 UTC, samar-hassan approved these changes

2024-02-07 23:22 UTC, merged