Add prepare save method to make it possible to bulk save attributes
django-oscar/django-oscar pull request #4209
Opened 2023-11-27 15:59 UTC by viggo-devries

2023-12-02 20:30 UTC, specialunderwear requested changes

2023-12-20 17:24 UTC, viggo-devries commented on src/oscar/apps/catalogue/product_attributes.py
> +            return (to_be_deleted, update_fields, to_be_updated, to_be_created)
Check again

2023-12-27 14:49 UTC, samar-hassan approved these changes

2023-12-28 07:54 UTC, nathanhighbiza approved these changes

2023-12-28 09:06 UTC, merged